"""create operational PostgreSQL schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_operational_schema"
down_revision = None
branch_labels = None
depends_on = None
J = postgresql.JSONB

def upgrade():
    op.create_table("users", sa.Column("id", sa.String(128), primary_key=True), sa.Column("username", sa.String(255), nullable=False, unique=True), sa.Column("password_hash", sa.Text, nullable=False), sa.Column("role", sa.String(32), nullable=False), sa.Column("active", sa.Boolean, nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("last_login_at", sa.DateTime(timezone=True)))
    op.create_table("clients", sa.Column("id", sa.String(128), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("client_group", sa.String(255), nullable=False), sa.Column("active", sa.Boolean, nullable=False, server_default=sa.true()), sa.Column("grupo", sa.String(255)), sa.Column("cota", sa.String(255)), sa.Column("versao", sa.String(255)), sa.Column("variables", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("notes", sa.Text, nullable=False, server_default=""), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("actions", sa.Column("id", sa.String(255), primary_key=True), sa.Column("key", sa.String(255), nullable=False, unique=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("description", sa.Text, nullable=False, server_default=""), sa.Column("status", sa.String(32), nullable=False, server_default="published"), sa.Column("published_version_id", sa.String(128)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("action_versions", sa.Column("id", sa.String(128), primary_key=True), sa.Column("action_id", sa.String(255), sa.ForeignKey("actions.id", ondelete="CASCADE"), nullable=False), sa.Column("version_number", sa.Integer, nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="published"), sa.Column("created_by", sa.String(255)), sa.Column("source_version_id", sa.String(128)), sa.Column("definition", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("variables", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("metadata", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("published_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("action_id", "version_number", name="uq_action_version_number"))
    op.create_foreign_key("fk_actions_published_version", "actions", "action_versions", ["published_version_id"], ["id"], ondelete="SET NULL")
    op.create_table("action_steps", sa.Column("id", sa.String(128), primary_key=True), sa.Column("action_version_id", sa.String(128), sa.ForeignKey("action_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("step_index", sa.Integer, nullable=False), sa.Column("step_type", sa.String(128), nullable=False, server_default="unknown"), sa.Column("selector", sa.Text), sa.Column("variable_key", sa.String(255)), sa.Column("step_data", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("action_version_id", "step_index", name="uq_action_step_index"))
    op.create_table("extraction_contracts", sa.Column("id", sa.String(128), primary_key=True), sa.Column("action_version_id", sa.String(128), sa.ForeignKey("action_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("target_name", sa.String(255), nullable=False), sa.Column("screen_label", sa.String(255), nullable=False, server_default=""), sa.Column("selection_type", sa.String(64), nullable=False, server_default="text"), sa.Column("value_type", sa.String(64), nullable=False, server_default="string"), sa.Column("return_format", sa.String(64), nullable=False, server_default="text"), sa.Column("selector_data", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("anchor_data", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("validation_data", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("example_value", sa.Text), sa.Column("summary_instruction", sa.Text), sa.Column("status", sa.String(32), nullable=False, server_default="active"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("batches", sa.Column("id", sa.String(128), primary_key=True), sa.Column("action_id", sa.String(255), sa.ForeignKey("actions.id", ondelete="SET NULL")), sa.Column("action_version_id", sa.String(128), sa.ForeignKey("action_versions.id", ondelete="SET NULL")), sa.Column("client_group", sa.String(255)), sa.Column("status", sa.String(64), nullable=False), sa.Column("delay_seconds", sa.Float, nullable=False, server_default="0"), sa.Column("total_items", sa.Integer, nullable=False, server_default="0"), sa.Column("processed_items", sa.Integer, nullable=False, server_default="0"), sa.Column("success_items", sa.Integer, nullable=False, server_default="0"), sa.Column("error_items", sa.Integer, nullable=False, server_default="0"), sa.Column("cancel_requested", sa.Boolean, nullable=False, server_default=sa.false()), sa.Column("idempotency_key", sa.String(255), unique=True), sa.Column("created_by", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("heartbeat_at", sa.DateTime(timezone=True)), sa.Column("metadata", J, nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.create_table("runs", sa.Column("id", sa.String(128), primary_key=True), sa.Column("action_id", sa.String(255), sa.ForeignKey("actions.id", ondelete="SET NULL")), sa.Column("action_version_id", sa.String(128), sa.ForeignKey("action_versions.id", ondelete="SET NULL")), sa.Column("client_id", sa.String(128), sa.ForeignKey("clients.id", ondelete="SET NULL")), sa.Column("batch_id", sa.String(128), sa.ForeignKey("batches.id", ondelete="SET NULL")), sa.Column("status", sa.String(64), nullable=False), sa.Column("runner", sa.String(128)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("result_summary", sa.Text), sa.Column("extracted_data", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("input_variables", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("diagnostics", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("step_trace", J, nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("error_data", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("screenshot_path", sa.Text), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("batch_items", sa.Column("id", sa.String(128), primary_key=True), sa.Column("batch_id", sa.String(128), sa.ForeignKey("batches.id", ondelete="CASCADE"), nullable=False), sa.Column("client_id", sa.String(128), sa.ForeignKey("clients.id", ondelete="SET NULL")), sa.Column("position", sa.Integer, nullable=False), sa.Column("status", sa.String(64), nullable=False), sa.Column("run_id", sa.String(128), sa.ForeignKey("runs.id", ondelete="SET NULL")), sa.Column("input_variables", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("result_data", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("error_data", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("retry_count", sa.Integer, nullable=False, server_default="0"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("batch_id", "position", name="uq_batch_item_position"))
    op.create_table("schedules", sa.Column("id", sa.String(128), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("action_id", sa.String(255), sa.ForeignKey("actions.id", ondelete="SET NULL")), sa.Column("client_group", sa.String(255)), sa.Column("frequency", sa.String(128), nullable=False), sa.Column("timezone", sa.String(128), nullable=False, server_default="UTC"), sa.Column("schedule_config", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("delay_seconds", sa.Float, nullable=False, server_default="0"), sa.Column("active", sa.Boolean, nullable=False, server_default=sa.true()), sa.Column("next_run_at", sa.DateTime(timezone=True)), sa.Column("last_run_at", sa.DateTime(timezone=True)), sa.Column("created_by", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("external_systems", sa.Column("id", sa.String(128), primary_key=True), sa.Column("name", sa.String(255), nullable=False, unique=True), sa.Column("config", J, nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("desktop_view_tokens", sa.Column("digest", sa.String(128), primary_key=True), sa.Column("purpose", sa.String(128), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False))

def downgrade():
    for table in ("desktop_view_tokens", "external_systems", "schedules", "batch_items", "runs", "batches", "extraction_contracts", "action_steps"):
        op.drop_table(table)
    op.drop_constraint("fk_actions_published_version", "actions", type_="foreignkey")
    op.drop_table("action_versions")
    op.drop_table("actions")
    op.drop_table("clients")
    op.drop_table("users")
