/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ExecucaoRouteImport } from './routes/execucao'
import { Route as EnsinarAcaoRouteImport } from './routes/ensinar-acao'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as AcoesRouteImport } from './routes/acoes'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecucaoRoute = ExecucaoRouteImport.update({
  id: '/execucao',
  path: '/execucao',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsinarAcaoRoute = EnsinarAcaoRouteImport.update({
  id: '/ensinar-acao',
  path: '/ensinar-acao',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesRoute = AcoesRouteImport.update({
  id: '/acoes',
  path: '/acoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acoes': typeof AcoesRoute
  '/agendamentos': typeof AgendamentosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/ensinar-acao': typeof EnsinarAcaoRoute
  '/execucao': typeof ExecucaoRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acoes': typeof AcoesRoute
  '/agendamentos': typeof AgendamentosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/ensinar-acao': typeof EnsinarAcaoRoute
  '/execucao': typeof ExecucaoRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acoes': typeof AcoesRoute
  '/agendamentos': typeof AgendamentosRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/ensinar-acao': typeof EnsinarAcaoRoute
  '/execucao': typeof ExecucaoRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acoes'
    | '/agendamentos'
    | '/clientes'
    | '/configuracoes'
    | '/diagnostico'
    | '/ensinar-acao'
    | '/execucao'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acoes'
    | '/agendamentos'
    | '/clientes'
    | '/configuracoes'
    | '/diagnostico'
    | '/ensinar-acao'
    | '/execucao'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/acoes'
    | '/agendamentos'
    | '/clientes'
    | '/configuracoes'
    | '/diagnostico'
    | '/ensinar-acao'
    | '/execucao'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcoesRoute: typeof AcoesRoute
  AgendamentosRoute: typeof AgendamentosRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EnsinarAcaoRoute: typeof EnsinarAcaoRoute
  ExecucaoRoute: typeof ExecucaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execucao': {
      id: '/execucao'
      path: '/execucao'
      fullPath: '/execucao'
      preLoaderRoute: typeof ExecucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensinar-acao': {
      id: '/ensinar-acao'
      path: '/ensinar-acao'
      fullPath: '/ensinar-acao'
      preLoaderRoute: typeof EnsinarAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes': {
      id: '/acoes'
      path: '/acoes'
      fullPath: '/acoes'
      preLoaderRoute: typeof AcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcoesRoute: AcoesRoute,
  AgendamentosRoute: AgendamentosRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EnsinarAcaoRoute: EnsinarAcaoRoute,
  ExecucaoRoute: ExecucaoRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
